#!/bin/bash
#
#	/etc/init.d/Daemon
#
# Starts the at daemon
#
# chkconfig: 345 95 5
# description: Runs the SM_NagiosConfigurator daemon.
# processname: daemon.php
 
# Source function library.
. /lib/lsb/init-functions
 
#startup values
log=/var/log/SM_NagiosConfigurator.log
 
#verify that the executable exists
test -x /var/www/IcaroSM/apps/plugins/Nagios/daemon.php || exit 0RETVAL=0
 
#
#	Set prog, proc and bin variables.
#
prog="SM_NagiosConfigurator"
proc=/var/lock/subsys/SM_NagiosConfigurator
bin="daemon.php"
pidfile="/var/run/$prog.pid"
 
start() {
	# Check if Daemon is already running
	if [ ! -f $proc ]; then
	    echo -n $"Starting $prog:"
	    daemon  -F $pidfile -o "/var/log/sm_dmn.log" -D "/var/www/IcaroSM/apps/plugins/Nagios" -U "./$bin" -- --log=$log --lock=$proc
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch $proc
	    echo -e "\t\t\t\t[\e[1;32mOK\e[0m]"
	fi
 
	return $RETVAL
}
 
stop() {
	
	#killproc $bin -TERM
	if [ -f $pidfile ]; then
		echo -n $"Stopping $prog:"
		kill -9 `cat $pidfile`
        	killall -9 $bin
		RETVAL=$?
		[ $RETVAL -eq 0 ] && rm -f $proc && rm -f $pidfile && rm -f $log
		echo -e "\t\t\t\t[\e[1;31mSTOPPED\e[0m]"
       	 return $RETVAL
	fi
 
	return $RETVAL

}
 
restart() {
	stop
	start
}	
 
reload() {
	restart
}	
 
status_at() {
 	status $bin
}
 
case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
        if [ -f $proc ]; then
            restart
        fi
        ;;
status)
	status_at
	;;
*)
 
echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac
 
exit $?
exit $RETVAL